# .github/workflows/deploy.yaml

on:
  push:
    branches: [main]

name: Deploy pkgdown site

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy docs/ to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs
          clean: false

